#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run_desktop"

[ ! -d "$cachedir" ] && mkdir -p "$cachedir"

dirs=""

IFS=:
for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share}; do
    dirs="$dirs:$dir/applications"
done

dirs="${dirs#:}"

if stest -dqr -n "$cache" $PATH; then
    > "$cache"
    for dir in $dirs; do
        stest -fl "$dir" \
            | grep -v 'mimeinfo.cache' \
            | grep -v -i 'wine' \
            | grep -v -i '^.*URI-' \
            | grep -v -i '^.*URL-' \
            | while IFS= read -r file; do
                full_path="$dir/$file"
                name=$(grep -m1 '^Name[en_US]=' "$full_path" | cut -d= -f2-)
                if [ -z "$name" ]; then
                    name=$(grep -m1 '^Name=' "$full_path" | cut -d= -f2-)
                fi
                [ -n "$name" ] && echo "$name:$full_path"
            done
    done \
    | grep -v -F -x -e "Dmenu Launch:" \
                    -e "Qt V4L2 video capture utility:" \
                    -e "Autorun Prompt:" \
                    -e "Eye of GNOME:" \
                    -e "Qt V4L2 test Utility:" \
                    -e "umpv Media Player:" \
                    -e "compton:" \
                    -e "picom:" \
                    -e "XDG Assist:" \
                    -e "ProtonUp-Qt:" \
                    -e "Run Command:" \
                    -e "XDG Launch:" \
                    -e "GTK+ Demo:" \
    | sort -u \
    | awk -F: '!seen[$1]++' > "$cache"
fi
cut -d: -f1 "$cache"
